import Link from "next/link";
import "./globals.css";
import Loginbtn from "./loginbtn";
import {getServerSession} from "next-auth";
import {authOptions} from "@/pages/api/auth/[...nextauth]";
import Logoutbtn from "./logoutbtn";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({children}) {
  let session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body>
        <div className="navbar">
          <Link href="/" className="logo">
            Appleforum
          </Link>
          <Link href="/list">List</Link>
          <Link href="/write">Write</Link>
          <div>
            {session ? (
              <span>
                {session.user.name} <Logoutbtn />
              </span>
            ) : (
              <Loginbtn />
            )}
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
